name: Android Release

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  buid:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Step up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      # - name: Version Bump
      #   uses: chkfung/android-version-actions@v1.2.3
      #   with:
      #     gradlePath: app/build.gradle
      #     versionCode: ${{ github.run_number }}

      # - name: Assmble Release Bundle
      #   run: ./gradlew bundleRelease

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - run: flutter pub get
      - run: flutter --version
      
      # - run: flutter build apk --release --split-per-abi
      - run: flutter build apk --release 

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          storeFile: "meta/upload-keystore.jks"
          releaseDirectory: build/app/outputs/bundle/release
          signingKeyBase64: ${{ secrets.APP_KEYSTORE }}
          keyStorePassword: ${{secrets.APP_PASSWORD}}
          alias: ${{secrets.APP_ALIAS}}
          keyPassword: ${{secrets.APP_ALIAS_PASSWORD}}


      - name: Push to release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: "v0.0${{ github.run_number }}"
          token: ${{secrets.APP_KEYSTORE}}
