name: Build Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17' # Use your project's Java version

      - name: Decode and save keystore file
        env:
          KEYSTORE_BASE64: ${{ secrets.APP_KEYSTORE }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/release-key.keystore
          echo "Keystore file created."

      - name: Set environment variables
        run: |
          echo "KEYSTORE_PATH=android/app/release-key.keystore" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV


      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      - run: flutter pub get
      - run: flutter --version
      
      - run: flutter build apk --release 

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
