name: iOS Release

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  deoployIos:
    runs-on: macos-latest
    env:
      ASC_JSON_KEY: ${{secrets.ASC_JSON_KEY}}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{secrets.APPLE_PASSWORD}}
      # FASTLANE_PASSWORD: ${{secrets.FASTLANE_PASSWORD}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Step Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          # channel: "stable"
          # cache: true 
        id: flutter
      - name: Get Packages
        run: flutter pub get
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
          working-directory: ios
      - name: Setup app store connect
        run: echo "$ASC_STORE_JSON" >> ./ios/fastlane/store.json
      - name: Install pod
        run: cd ios && pod install
      - name: Build and Deploy to testflight
        env:
          MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{secrets.MATCH_GIT_BASIC_AUTHORIZATION}}

        run: |
          cd ./ios
          bundle exec fastlane ios beta
